Add coverage and build stages
utwente-fmt/vercors pull request #487
Opened 2020-07-15 15:04 UTC by bobismijnnaam

This pull request refactors the build system to use stages so intermediate files can be communicated. It also adds support for sonarcloud coverage reporting through integration of Jacoco in the vercors test suite.

2021-01-26 16:25 UTC, bobismijnnaam commented
I think this PR will be subsumed by #578 and the recent move to github actions (which enables trivial file sharing, which was not possible before). Until then we keep this PR around in case it proves useful in the future, but I think it won't be needed if #578 works out.

2021-07-08 13:44 UTC, Vescatur requested changes
There are two jars added to the git repository (jacocoagant.jar and jacococli.jar) . Is that necessary or can they added as a dependency? If you choose to remove them, could you also remove them from the git history to save on storage?

2021-07-08 13:44 UTC, Vescatur commented on .github/workflows/build-test-slow-medium.yml.disabled
> +name: Vercors build and test workflow for the slow and medium test suites. Currently disabled as some work is needed to get the slow/medium suites to pass again.
Could you remove this document?

2021-07-08 13:44 UTC, Vescatur commented on .github/workflows/build-test.yml
> +      - run: vercorszip\bin\vercors.bat --test=examples\basic --test-workers=2 --tool carbon --tool silicon """--exclude-suite=slow,medium,problem-fail,skip-travis""" --progress --actions-test-output
skip-travis is not needed anymore. 

Could you merge dev into this branch to check whether my changes are compatible with yours?

2021-07-08 13:44 UTC, Vescatur commented on .github/workflows/build-test.yml
> +  integration-test-mac:
I think it is nice that we are testing on all the operating systems.

2021-07-08 13:44 UTC, Vescatur commented on examples/verifythis/2018/challenge1.pvl
> -// -*- tab-width:2 ; indent-tabs-mode:nil -*-
I will check whether this document is in the correct directory after merging.

2021-07-08 13:44 UTC, Vescatur commented on examples/verifythis/2018/challenge2.pvl
Should be in known-problems which it will probably will be after merging.

2021-07-08 13:50 UTC, Vescatur commented
I think it is easier to merge pull request that focus on one problem. This pull request fixes an example, expanded the test suite so that it runs on other operating systems and does code coverage. I think these separate features could have already been merged with dev before everything was finished.

2021-07-08 13:57 UTC, Vescatur commented
> There are two jars added to the git repository (jacocoagant.jar and jacococli.jar) . Is that necessary or can they added as a dependency? If you choose to remove them, could you also remove them from the git history to save on storage?

I see that the project is already 700 mb so might not be really relevant.

2021-07-08 14:08 UTC, bobismijnnaam commented
> I think it is easier to merge pull request that focus on one problem. This pull request fixes an example, expanded the test suite so that it runs on other operating systems and does code coverage. I think these separate features could have already been merged with dev before everything was finished.

I agree, this PR got out of hand. I'll pay better attention next time :)

> I see that the project is already 700 mb so might not be really relevant.

All the little bits add up, so I agree that we should be on the lookout for them. But in this case it cannot be avoided I think.

2021-07-12 09:24 UTC, Vescatur approved these changes
I appreciate the effort into decreasing the nesting of CommandLineTesting. The rest of the pull request also looks good.

2021-07-12 09:30 UTC, merged